name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to push to the repository
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history to merge
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/snailyp/zai-proxy.git
          git fetch upstream
          
          # Assuming the default branch is the one to be synced
          # This will get the name of the current branch (e.g., main)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Merge changes from upstream's main branch
          # Using --no-edit to automatically accept the default merge commit message
          # Using --allow-unrelated-histories in case the fork was created without a common ancestor
          git merge upstream/main --no-edit --allow-unrelated-histories
          
          # Push the merged changes
          git push origin $CURRENT_BRANCH
